---
# Parameters used to build the Marshall Island model.
default:

  # Model structure parameters
  n_exposed_compartments: 2
  n_infectious_compartments: 2

  # Age-specific infectiousness progression adjustments - in ten year brackets
  age_infect_progression:
    - 0.09
    - 0.33
    - 0.67
    - 0.4
    - 0.43
    - 0.51
    - 0.5
    - 0.46

  # Age-specific CFR - in five year brackets
  age_cfr:
    - 0.00019
    - 0.00046
    - 0.0019
    - 0.0038
    - 0.0082
    - 0.027
    - 0.094
    - 0.2
    - 0.36
  high_infect_multiplier: 1.
  low_infect_multiplier: 0.

  # Add non-infectious
  add_non_infectious: True

  # Country for mixing matrix
  country: Australia

  # Initial conditions
  infectious_seed: 2000

  # Stratifications to implement - comment out/remove as required to enable model to run more quickly
  stratify_by:
    - agegroup
    - infectiousness
  all_stratifications: {}
  agegroup_breaks:
    - 80
    - 5
  start_time: 0.
  end_time: 150.
  time_step: 1

  # Base model definition
  contact_rate: 0.7
  latent_period: 3.2
  infectious_period: 7.68
  universal_death_rate: 0.
  infect_death: 0.

  incidence_stratification:
    - agegroup

# When the scenarios start running
scenario_start: 50

# N.B: Scenario keys have to be integers 1-N, or it'll break downstream dashboards.
scenarios: {}
#  1: {}
