---
# Parameters used to build the Marshall Island model.
default:

  # Model structure parameters
  n_exposed_compartments: 2
  n_infectious_compartments: 2

  # Add non-infectious
  add_non_infectious: True

  # Country for mixing matrix
  country: Australia

  # Initial conditions
  infectious_seed: 2000

  # Stratifications to implement - comment out/remove as required to enable model to run more quickly
  stratify_by:
    - agegroup
    - infectiousness
  all_stratifications: {}
  agegroup_breaks:
    - 80
    - 5
  start_time: 0.
  end_time: 150.
  time_step: 1

  # Base model definition
  contact_rate: 0.3
  latent_period: 3.2
  infectious_period: 7.68
  universal_death_rate: 0.

# When the scenarios start running
scenario_start: 10

# N.B: Scenario keys have to be integers 1-N, or it'll break downstream dashboards.
scenarios: {}
