---
# Parameters used to build the Marshall Island model.
default:

  # Model structure parameters
  n_compartment_repeats: 2

  # Age-specific infectiousness progression adjustments - in ten year brackets
  age_infect_progression:
    - 0.09
    - 0.33
    - 0.67
    - 0.4
    - 0.43
    - 0.51
    - 0.5
    - 0.46
# Ferguson infect proportion 40-50%
# Infection fatality rate of 0.9% and 4.4% infections hospitalised
# 30% hospitalised need ICU
# 50% ICU cases die (supplemented by non-critical care deaths to reach age-specific IFR)
# 8 days in hospital if no ICU
# 16 days in hospital if ICU needed
# Ferguson table 1 gives age-specific hospital|symptoms, ICU|hospital, IFR

  hospital_props:
    - 0.001
    - 0.003
    - 0.012
    - 0.032
    - 0.049
    - 0.102
    - 0.166
    - 0.243
    - 0.273
  icu_props:
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.063
    - 0.122
    - 0.274
    - 0.432
    - 0.709

  # Age-specific CFR - in five year brackets
  age_cfr:
    - 0.00019
    - 0.00046
    - 0.0019
    - 0.0038
    - 0.0082
    - 0.027
    - 0.094
    - 0.2
    - 0.36
# Ruiyun et al. in Science - 0.55
  low_infect_multiplier: 0.

  # Add non-infectious
  add_non_infectious: True

  # Country for mixing matrix
  country: Australia

  # Initial conditions
  infectious_seed: 2000

  # Stratifications to implement - comment out/remove as required to enable model to run more quickly
  stratify_by:
    - agegroup
    - infectiousness
  all_stratifications: {}
  agegroup_breaks:
    - 80
    - 5
  start_time: 0.
  end_time: 150.
  time_step: 1

  # Base model definition
  contact_rate: 0.75
  exposed_period: 3.2
  presympt_period: 0.5
  infectious_period: 7.68
  universal_death_rate: 0.
  infect_death: 0.

  # Ferguson parameters
#  exposed_period: 5.1
#  presympt_period: 0.5
#  infectious_period: unclear, differs by symptoms
#  high_infect_multiplier: 1.5
#  low_infect_multiplier: 1.

  incidence_stratification:
    - agegroup

# When the scenarios start running
scenario_start: 60

# N.B: Scenario keys have to be integers 1-N, or it'll break downstream dashboards.
scenarios: {}
#  1:
#    mixing:
#      school: -1.
#  2:
#    mixing:
#      school: -1.
#      home: 0.1
#  3:
#    mixing:
#      school: -1.
#      home: 0.2
#  4:
#    mixing:
#      work: -1.
#  5:
#    mixing:
#      work: -1.
#      home: 0.1
#  6:
#    mixing:
#      work: -1.
#      home: 0.2
#  7:
#    mixing:
#      school: -0.4
#      work: -0.4
#      other_locations: -0.4
#  8:
#    mixing:
#      school: -0.4
#      work: -0.4
#      other_locations: -0.4
#      home: 0.1
#  9:
#    mixing:
#      school: -0.4
#      work: -0.4
#      other_locations: -0.4
#      home: 0.2
#  10:
#    mixing:
#      school: -0.8
#      work: -0.8
#      other_locations: -0.8
#  11:
#    mixing:
#      school: -0.8
#      work: -0.8
#      other_locations: -0.8
#      home: 0.1
#  12:
#    mixing:
#      school: -0.8
#      work: -0.8
#      other_locations: -0.8
#      home: 0.2
