---
# Parameters used to build the Marshall Island model.
default:

  # Model structure parameters
  n_exposed_compartments: 2
  n_infectious_compartments: 2

  # Initial conditions
  infectious_seed: 1

  # Stratifications to implement - comment out/remove as required to enable model to run more quickly
  stratify_by:
    - agegroup
  all_stratifications: {}
  agegroup_breaks:
    - 80
    - 5
  start_time: 0.
  end_time: 100.
  time_step: 1
  start_population: 1000

  # Base model definition
  contact_rate: 1.
  progression: 0.2
  recovery: 0.125
  universal_death_rate: 0.

# When the scenarios start running
scenario_start: 10

# N.B: Scenario keys have to be integers 1-N, or it'll break downstream dashboards.
scenarios: {}
