---
# Parameters used to build a general model of COVID-19 disease for application to Australia or internationally
default:

  # MODEL STRUCTURE PARAMETERS

  # Number of times each compartment representing active infection (i.e. not S and not R) are repeated
  n_compartment_repeats: 2

  # Stratification-related requests
  stratify_by:
    - agegroup
    - infectiousness
  agegroup_breaks:
    - 80
    - 5

  # AGE-STRATIFIED PARAMETERS

  # Infectiousness progression adjustments - in ten year brackets that need to adapated to model strata later
  symptomatic_props:
    - 0.09
    - 0.33
    - 0.67
    - 0.4
    - 0.43
    - 0.51
    - 0.5
    - 0.46

  # Proportion hospitalised
  hospital_props:
    - 0.001
    - 0.003
    - 0.012
    - 0.032
    - 0.049
    - 0.102
    - 0.166
    - 0.243
    - 0.273

  # Proportion admitted to ICU
  icu_props:
    - 0.05
    - 0.05
    - 0.05
    - 0.05
    - 0.063
    - 0.122
    - 0.274
    - 0.432
    - 0.709

  # Infection fatality proportions
  infection_fatality_props:
    - 0.00002
    - 0.00006
    - 0.0003
    - 0.0008
    - 0.0015
    - 0.006
    - 0.022
    - 0.051
    - 0.093

  # NON-AGE-STRATIFIED PARAMETERS

  # Ruiyun et al. in Science - 0.55
  low_infect_multiplier: 0.55

  # Add non-infectious
  add_non_infectious: True

  # Country to extract Prem mixing matrix from
  country: Australia

  # Country to extract stratified population data from - should eventually use only one of country or iso3
  iso3: AUS

  # Initial conditions
  infectious_seed: 100

  # Running time-related - for COVID-19 model, all times are assumed to be in days and reference time is 1st Jan 2020
  start_time: 51.
  end_time: 250.
  time_step: 1

  # Base model definition
  contact_rate: 0.397082
  exposed_period: 3.2
  presympt_period: 0.5
  infectious_period: 7.68
  hospital_period: 8.
  icu_period: 20.
  universal_death_rate: 0.
  infect_death: 0.

# SCENARIO-RELATED PARAMETERS

# When the scenarios start running
scenario_start: 85

# N.B: Scenario keys have to be sequential integers from one, or won't be compatible with dashboards
scenarios: {}
#  1:
#    mixing:
#      school: -1.
#  2:
#    mixing:
#      school: -1.
#      home: 0.1
#  3:
#    mixing:
#      school: -1.
#      home: 0.2
#  4:
#    mixing:
#      work: -1.
#  5:
#    mixing:
#      work: -1.
#      home: 0.1
#  6:
#    mixing:
#      work: -1.
#      home: 0.2
#  7:
#    mixing:
#      school: -0.4
#      work: -0.4
#      other_locations: -0.4
#  8:
#    mixing:
#      school: -0.4
#      work: -0.4
#      other_locations: -0.4
#      home: 0.1
#  9:
#    mixing:
#      school: -0.4
#      work: -0.4
#      other_locations: -0.4
#      home: 0.2
#  10:
#    mixing:
#      school: -0.8
#      work: -0.8
#      other_locations: -0.8
#  11:
#    mixing:
#      school: -0.8
#      work: -0.8
#      other_locations: -0.8
#      home: 0.1
#  12:
#    mixing:
#      school: -0.8
#      work: -0.8
#      other_locations: -0.8
#      home: 0.2
